### ISSUE TITLE
it always rerun all gulp task when watch trigger server.run

### ISSUE THREAD

**Issue by zzswang** [gimm/gulp-express#3]
it always rerun all gulp task when watch trigger server.run.

I use the sample gulpfile.js in the readme.

**Comment by simevidas** [comment]
@gimm Unfortunately not. I still have this issue (and another user as well: https://github.com/gimm/gulp-express/issues/18). cc @thiagomata

**Comment by simevidas** [comment]
I’m happy to report that I’ve managed to make it work correctly. Here is an excerpt of my gulpfile:

```js
var gulp = require('gulp');
var server = require('gulp-express');
var livereload = require('gulp-livereload');
// etc.

gulp.task('server', function () {
	server.run({ port: 35730 });
	
	gulp.watch('source/styl/*.styl', ['build-css']);
	gulp.watch(['app.js', 'routes/*.js'], function (e) {
		server.run({ port: 35730 });
		livereload.changed(e.path);
	});
});

gulp.task('build-css', function () {
	return gulp.src('source/styl/*.styl')
		.pipe(stylus({ compress: false, 'include css': true }))
		// other tasks
		.pipe(gulp.dest('public/css/'))
		.pipe(livereload());
});
```

A note regarding my use of gulp-livereload: I’m using this plugin to manually handle refresh in the browser. I’m doing this because `server.notify` cannot be nicely integrated into `.watch()` arguments when there are other tasks listed (`['build-css']` in my code). There is the workaround with using a callback function (described in the README of this repo) which I haven’t tried, but that code pattern does not seem optimal, so I’ve decided to run a custom livereload server using gulp-livereload. Notice how it can be easily hooked up to my "build-css" task by simply piping it at the end (`.pipe(livereload())`). It would be great if `server.notify` supported an analogous approach.
